version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
#  api:
#    build:
#      context: .
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#    ports:
#      - '3000:3000'


volumes:
  postgres:
